// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernWMS.Core.DBContext;

#nullable disable

namespace ModernWMS.Migrations
{
    [DbContext(typeof(SqlDBContext))]
    partial class SqlDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("ModernWMS.Core.Models.UserroleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("userrole");
                });

            modelBuilder.Entity("ModernWMS.Core.Models.userEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("auth_string")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("user_num")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("user_role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("actual_qty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("asn_no")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("asn_qty")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("asn_status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("damage_qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("goods_owner_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("more_qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("shortage_qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sku_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sorted_qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("spu_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("supplier_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("volume")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("weight")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("asn");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnsortEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("asn_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("sorted_qty")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("asnsort");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.CategoryEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("parent_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.CompanyEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.CustomerEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchlistEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("actual_qty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("carrier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("customer_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("damage_qty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dispatch_no")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("dispatch_status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("freightfee")
                        .HasColumnType("TEXT");

                    b.Property<int>("intrasit_qty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("lock_qty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("package_no")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("package_person")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("package_qty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("package_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("picked_qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sign_qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sku_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("volume")
                        .HasColumnType("TEXT");

                    b.Property<string>("waybill_no")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("weighing_no")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("weighing_person")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("weighing_qty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("weighing_weight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("weight")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("dispatchlist");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchpicklistEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("dispatchlist_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("pick_qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("picked_qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sku_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("dispatchlist_id");

                    b.ToTable("dispatchpicklist");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FreightfeeEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("arrival_city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("carrier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("departure_city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("min_payment")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("price_per_volume")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("price_per_weight")
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("freightfee");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.GoodslocationEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("layer_number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("location_heigth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("location_length")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("location_load")
                        .HasColumnType("TEXT");

                    b.Property<string>("location_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("location_volume")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("location_width")
                        .HasColumnType("TEXT");

                    b.Property<string>("roadway_number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("shelf_number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tag_number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("warehouse_area_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("warehouse_area_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("warehouse_area_property")
                        .HasColumnType("INTEGER");

                    b.Property<int>("warehouse_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("warehouse_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("goodslocation");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.GoodsownerEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("goods_owner_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("goodsowner");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.MenuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("menu_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("module")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("sort")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("vue_directory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vue_path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vue_path_detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("menu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.RolemenuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("authority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("menu_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("userrole_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("rolemenu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("height")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("lenght")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("price")
                        .HasColumnType("TEXT");

                    b.Property<string>("sku_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sku_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("spu_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("volume")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("weight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("width")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("spu_id");

                    b.ToTable("sku");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SpuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("bar_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("category_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<byte>("length_unit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("spu_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("spu_description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("spu_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("supplier_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("volume_unit")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("weight_unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("spu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_freeze")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sku_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("stock");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockadjustEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("job_type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sku_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("source_table_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("stockadjust");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockfreezeEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("handle_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("job_type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("sku_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("stockfreeze");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockmoveEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("dest_googs_location_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("handle_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<byte>("move_status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("orig_goods_location_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sku_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("stockmove");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockprocessEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("job_type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<bool>("process_status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("process_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("processor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("stockprocess");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockprocessdetailEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_source")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sku_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("stock_process_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("stock_process_id");

                    b.ToTable("stockprocessdetail");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StocktakingEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("book_qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("counted_qty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("difference_qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("handle_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("job_status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("sku_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("stocktaking");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SupplierEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("supplier");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.WarehouseEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("warehouse_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("warehouse");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.WarehouseareaEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("area_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("area_property")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_valid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("parent_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("tenant_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("warehouse_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("warehousearea");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchpicklistEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.DispatchlistEntity", "Dispatchlist")
                        .WithMany("detailList")
                        .HasForeignKey("dispatchlist_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispatchlist");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.SpuEntity", "Spu")
                        .WithMany("detailList")
                        .HasForeignKey("spu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockprocessdetailEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.StockprocessEntity", "Stockprocess")
                        .WithMany("detailList")
                        .HasForeignKey("stock_process_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stockprocess");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchlistEntity", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SpuEntity", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockprocessEntity", b =>
                {
                    b.Navigation("detailList");
                });
#pragma warning restore 612, 618
        }
    }
}
